application: dev-code-labs
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /assets
  static_dir: assets

- url: /messages.php
  login: admin
  script: messages.php

- url: /welcome
  script: welcome.php

- url: /caching
  script: caching.php
  
- url: /how
  script: caching_how.php
  
- url: /example
  script: caching_example.php
  
- url: /who
  script: caching_who.php
  
- url: /memcached
  script: caching_memcache.php

- url: /memcached_setup
  script: caching_setup.php

  
- url: /end
  script: end.php

- url: .*
  script: main.php

